### ISSUE TITLE
Reservations and Nodes

### ISSUE THREAD

**Issue by stefan-k** [pkgw/slurm-rs#61]
Hi,

thanks for this crate! Are there any plans to extend the scope of this library beyond handling jobs? I'm particularly interested in setting/removing reservations and reading/changing properties of nodes.

**Comment by pkgw** [comment]
Thanks for reaching out! Due to where work has taken me lately, I'm not planning any particular organized development on this crate in the near future. I'll be happy to review and merge pull requests, though.

For what it's worth, I've found that the Slurm C API is not very stable — minor version updates will often change things so that you have to recompile the crate if not make source-level changes. In the end it might be easier to make a crate that does most of its work by executing the Slurm control programs (`sinfo` etc.) under the hood, rather than by trying to develop against the shared library.

**Comment by stefan-k** [comment]
Thanks for your quick and helpful reply! My next suggestion would have been to open a PR, but given that the API is not very stable I may as you said just shell out. Thanks! :)
